server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/users/**
        - id: exam-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/exams/**
        - id: question-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/questions/**
        - id: exam-session-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/sessions/**
        - id: result-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/results/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
